#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @version: 1.0
# @author: Nsirone
# @license: Apache Licence 
# @contact: nsirone@outlook.com
# @site: http://www.google.com
# @software: PyCharm Community Edition
# @file: ngrinder.py
# @time: 2016/5/5 18:13

# 搜索的压力测试

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP.
#
# This script is automatically generated by ngrinder.
#
# @author 倪雪鹏
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from HTTPClient import NVPair
import random
import linecache
import urllib

control = HTTPPluginControl.getConnectionDefaults()
# if you don't want that HTTPRequest follows the redirection, please modify the following option 0.
# control.followRedirects = 1
# if you want to increase the timeout, please modify the following option.
control.timeout = 6000

test1 = Test(1, "172.16.33.211")
request1 = HTTPRequest()

# Make any method call on request1 increase TPS
test1.record(request1)
test_query_file = "./resources/wordsKu.txt"
class TestRunner:
	# initlialize a thread
	def __init__(self):
		grinder.statistics.delayReports=True
		pass

	# test method
	def __call__(self):
		count = len(open(test_query_file,'rU').readlines())
		hellonum=random.randrange(1, count, 1)
		word = linecache.getline(test_query_file,hellonum)
		word = word.strip('\n')
		data = {
			'keyword':word
		}
		data = urllib.urlencode(data)
		print "http://172.16.33.211/all?"+data
		result = request1.GET("http://172.16.33.211/all?"+data)
		# You get the message body using the getText() method.
		# if result.getText().find("HELLO WORLD") != -1 :
		#    grinder.statistics.forLastTest.success = 1
		# else :
		#	 grinder.statistics.forLastTest.success = 0

		# if you want to print out log.. Don't use print keyword. Instead, use following.
		# grinder.logger.info("Hello World")

		if result.getStatusCode() == 200 :
			grinder.statistics.forLastTest.success = 1
		elif result.getStatusCode() in (301, 302) :
			grinder.logger.warn("Warning. The response may not be correct. The response code was %d." %  result.getStatusCode())
			grinder.statistics.forLastTest.success = 1
		else :
			grinder.statistics.forLastTest.success = 0
